##################
# Common Variables
##################

deploymentNamespace: argo-cd
server: https://kubernetes.default.svc


##################
# Version Manifest
##################

applicationVersions:
  frontend: &frontendVersion latest
  backend: &backendVersion f33770e5ffe6a06d85b6c63202a30720565328e6
  infinispan: &infinispanVersion 1.1.1.Final
  git-api: &gitApiVersion latest
  launcher: &launcherVersion latest


##################################
# Application Template Definitions
##################################

applications:
- name: omp-frontend
  url: https://github.com/rht-labs/open-management-portal-frontend.git
  ref: *frontendVersion
  helmValues:
    imageTag: *frontendVersion

- name: omp-backend
  url: https://github.com/rht-labs/open-management-portal-backend.git
  path: deployment
  ref: *backendVersion
  helmValues:
    imageTag: *backendVersion

- name: infinispan-operator
  url: https://github.com/infinispan/infinispan-operator.git
  path: deploy
  ref: *infinispanVersion

- name: git-api
  url: https://github.com/rht-labs/open-management-portal-git-api.git
  ref: *gitApiVersion
  helmValues:
    imageTag: *gitApiVersion

- name: omp-launcher
  url: https://github.com/redhat-cop/tool-integrations.git
  path: "argo-cd-bridges/gitlab/helm"
  ref: *launcherVersion

