##################
# Common Variables
##################

deploymentNamespace: argo-cd
server: https://kubernetes.default.svc


##################
# Version Manifest
##################

applicationVersions:
  frontend: &frontendVersion 38d978f63a2c887bb4c15ef9e91682c9981c64ae
  backend: &backendVersion 374f04aabd9a06a6eb44cecbdba8f40b1f3318c6
  infinispan: &infinispanVersion 1.1.1.Final
  git-api: &gitApiVersion 34f7566fc7330636206911f04e9dcd4f1408de9a
  launcher: &launcherVersion 3478f8caecf4198b73bdd3beb0efec42f322761a


##################################
# Application Template Definitions
##################################

applications:
- name: omp-frontend
  url: https://github.com/rht-labs/open-management-portal-frontend.git
  path: deployment
  ref: *frontendVersion
  helmValues:
    imageTag: *frontendVersion
    hostname: omp-frontend-omp.apps.test.omp.rht-labs.com
  diffIgnore:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status

- name: omp-backend
  url: https://github.com/rht-labs/open-management-portal-backend.git
  path: deployment
  ref: *backendVersion
  helmValues:
    imageTag: *backendVersion
    hostname: omp-backend-omp.apps.test.omp.rht-labs.com
  diffIgnore:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status

- name: infinispan-operator
  url: https://github.com/infinispan/infinispan-operator.git
  path: deploy
  ref: *infinispanVersion

- name: git-api
  url: https://github.com/rht-labs/open-management-portal-git-api.git
  path: deployment
  ref: *gitApiVersion
  helmValues:
    imageTag: *gitApiVersion

- name: omp-launcher
  url: https://github.com/redhat-cop/tool-integrations.git
  path: "argo-cd-bridges/gitlab/deploy"
  ref: *launcherVersion
  diffIgnore:
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /status

