##################
# Common Variables
##################

deploymentNamespace: argo-cd
server: https://kubernetes.default.svc


##################
# Version Manifest
##################

applicationVersions:
  infinispan: &infinispanVersion 1.1.1.Final
  launcher: &launcherVersion 3478f8caecf4198b73bdd3beb0efec42f322761a

##################################
# Application Template Definitions
##################################

applications:
- name: omp-frontend
  url: https://github.com/rht-labs/open-management-portal-frontend.git
  path: deployment
  diffIgnore:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image

- name: omp-backend
  url: https://github.com/rht-labs/open-management-portal-backend.git
  path: deployment
  helmValues:
    infinispanVersion: &infinispanVersion
    launcherVersion: &launcherVersion
  diffIgnore:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image

- name: infinispan-operator
  url: https://github.com/infinispan/infinispan-operator.git
  path: deploy
  ref: *infinispanVersion

- name: git-api
  url: https://github.com/rht-labs/open-management-portal-git-api.git
  path: deployment
  diffIgnore:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image

- name: omp-launcher
  url: https://github.com/redhat-cop/tool-integrations.git
  path: "argo-cd-bridges/gitlab/deploy"
  ref: *launcherVersion
  diffIgnore:
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /status

