apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd-clusterrolebindings.yaml
- argocd-operator-cr.yaml
- dex-deployment.yaml
patches:
  - patch: |
      - op: add
        path: /metadata/namespace
        value: lodestar-argo-cd
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ArgoCD
  - patch: |
      - op: replace
        path: /subjects/0/namespace
        value: lodestar-argo-cd
    target:
      labelSelector: app.kubernetes.io/part-of=argocd
      kind: ClusterRoleBinding
