{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
spec:
  destination:
    namespace: {{ $.Values.deploymentNamespace }}
    server: {{ $.Values.server }}
  project: default
  source:
    path: {{ .path | default "." | quote }}
    repoURL: {{ .url | quote }}
    targetRevision: {{ .ref | default "master" | quote }}
    {{- if .helmValues }}
    helm:
      values: |-
        {{- range $key, $value := .helmValues }}
        {{- if or (eq "map[string]interface {}" (printf "%T" $value)) (eq "[]interface {}" (printf "%T" $value))}}
        {{ $key }}: {{ $value | toJson }}
        {{- else }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{- end }}
    {{- end }}
  {{- if .diffIgnore }}
  ignoreDifferences:
  {{- range .diffIgnore }}
  - group: {{ .group }}
    kind: {{ .kind }}
    jsonPointers:
      {{- range .jsonPointers }}
      - {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
