name: Cancel Dispatch

on:
  repository_dispatch:
    types: [cancel-command]
jobs:
  promote-release:
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.NOTIFICATION_URL }}
    steps:
    - name: Set Env Variables
      id: env_info
      run: |
        ISSUE_TITLE=$(jq -r .client_payload.github.payload.issue.title $GITHUB_EVENT_PATH)
        echo ::set-output name=issuetitle::$ISSUE_TITLE
        echo ::set-output name=issuenm::$(jq .client_payload.github.payload.issue.number $GITHUB_EVENT_PATH)
        echo ::set-output name=requestor::$(jq -r .client_payload.github.actor $GITHUB_EVENT_PATH)
    - name: Delete branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ github.token }}
        branches: ${{ steps.env_info.outputs.issuetitle }}
    - name: Close Issue
      uses: peter-evans/close-issue@v1
      with:
        issue-number: ${{ steps.env_info.outputs.issuenm }}
        comment: Cancelling rollout as requested by @${{ steps.env_info.outputs.requestor }}.
    - name: Notify chat
      run: |
       echo "Thread key GIIHUB_REPOSITORY-${{ steps.env_info.outputs.issuenm }} requestor ${{ steps.env_info.outputs.requestor }}"
        [ ! -z "$URL" ] && curl "$URL&threadKey=$GIIHUB_REPOSITORY-${{ steps.env_info.outputs.issuenm}}" -H "Content-Type: application/json" -d '{ "text" : "\uD83E\uDDEF cancelling rollout as requested by ${{ steps.env_info.outputs.requestor }}" }'
