name: Chat Ops

on:
  issue_comment:
    types: [created]

jobs:
  launcher:
    runs-on: ubuntu-latest
    steps:
    - name: Command Dispatch
      uses: peter-evans/slash-command-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}
        commands: release, release-rc, promote, cancel, finish
        named-args: true
